/**
 * OpenAPI paths for every endpoint the SPA calls through frontend/src/api/client.js (#1368).
 *
 * Keyed by the client.js function that calls it (operationId). Served under /api/v1.
 * Endpoints with a richer @swagger JSDoc block in routes/*.js keep that definition;
 * this map fills in the rest so the spec covers the whole SPA surface.
 * tests/spaRoutes.contract.test.js fails if client.js gains a path missing here.
 */

'use strict';

const SPA_ENDPOINTS = [
  ['get', '/addresses', 'getAddresses'],
  ['post', '/addresses', 'createAddress'],
  ['delete', '/addresses/{id}', 'deleteAddress'],
  ['put', '/addresses/{id}', 'updateAddress'],
  ['patch', '/addresses/{id}/default', 'setDefaultAddress'],
  ['get', '/admin/contract-alerts', 'adminGetContractAlerts'],
  ['patch', '/admin/contract-alerts/{id}/acknowledge', 'adminAcknowledgeContractAlert'],
  ['get', '/admin/contracts', 'adminGetContracts'],
  ['post', '/admin/contracts', 'adminRegisterContract'],
  ['post', '/admin/contracts/deploy', 'adminDeployContract'],
  ['delete', '/admin/contracts/{id}', 'adminDeregisterContract'],
  ['get', '/admin/contracts/{registryId}/acl', 'adminGetContractAcl'],
  ['post', '/admin/contracts/{registryId}/acl', 'adminGrantContractAcl'],
  ['delete', '/admin/contracts/{registryId}/acl/{address}', 'adminRevokeContractAcl'],
  ['get', '/admin/contracts/{registryId}/compare', 'adminCompareContractVersions'],
  ['get', '/admin/contracts/{registryId}/invocations', 'adminGetContractInvocations'],
  ['get', '/admin/contracts/{registryId}/state/export', 'adminExportContractState'],
  ['post', '/admin/contracts/{registryId}/upgrade', 'adminRecordContractUpgrade'],
  ['get', '/admin/contracts/{registryId}/upgrades', 'adminGetContractUpgrades'],
  ['get', '/admin/orders', 'adminGetOrders'],
  ['get', '/admin/stats', 'adminGetStats'],
  ['get', '/admin/users', 'adminGetUsers'],
  ['delete', '/admin/users/{id}', 'adminDeactivateUser'],
  ['delete', '/admin/users/{id}/ban', 'adminUnbanUser'],
  ['post', '/admin/users/{id}/ban', 'adminBanUser'],
  ['get', '/analytics/farmer', 'getAnalytics'],
  ['get', '/analytics/farmer/forecast', 'getForecast'],
  ['get', '/analytics/farmer/waitlist', 'getWaitlistAnalytics'],
  ['get', '/announcements', 'getAnnouncements'],
  ['get', '/announcements/admin', 'adminGetAnnouncements'],
  ['post', '/announcements/admin', 'adminCreateAnnouncement'],
  ['delete', '/announcements/admin/{id}', 'adminDeleteAnnouncement'],
  ['patch', '/announcements/admin/{id}', 'adminUpdateAnnouncement'],
  ['get', '/auctions', 'getAuctions'],
  ['post', '/auctions', 'createAuction'],
  ['get', '/auctions/{id}', 'getAuction'],
  ['post', '/auctions/{id}/bid', 'placeBid'],
  ['get', '/auctions/{id}/bids', 'getAuctionBids'],
  ['patch', '/auctions/{id}/end', 'endAuction'],
  ['post', '/auth/2fa/disable', 'disable2FA'],
  ['post', '/auth/2fa/setup', 'setup2FA'],
  ['get', '/auth/2fa/status', 'get2FAStatus'],
  ['post', '/auth/2fa/verify', 'verify2FA'],
  ['delete', '/auth/account', 'deleteAccount'],
  ['get', '/auth/csrf-token', 'ensureCsrfToken'],
  ['post', '/auth/login', 'login'],
  ['post', '/auth/logout', 'logout'],
  ['get', '/auth/me', 'getCurrentUser'],
  ['patch', '/auth/me', 'updateProfile'],
  ['post', '/auth/recover', 'recoverAccount'],
  ['post', '/auth/refresh', 'refresh'],
  ['post', '/auth/register', 'register'],
  ['post', '/auth/seed-phrase', 'getSeedPhrase'],
  ['get', '/auth/stream-token', 'getWalletStreamUrl'],
  ['get', '/batches', 'getHarvestBatches'],
  ['post', '/batches', 'createHarvestBatch'],
  ['get', '/bundles', 'getBundles'],
  ['post', '/bundles', 'createBundle'],
  ['get', '/bundles/orders', 'getBundleOrders'],
  ['post', '/bundles/purchase', 'purchaseBundle'],
  ['delete', '/bundles/{id}', 'deleteBundle'],
  ['get', '/contracts/{contractId}/events', 'getContractEvents'],
  ['post', '/contracts/{contractId}/simulate', 'simulateContractCall'],
  ['get', '/contracts/{contractId}/state', 'getContractState'],
  ['get', '/cooperatives', 'getCooperatives'],
  ['post', '/cooperatives', 'createCooperative'],
  ['post', '/cooperatives/transactions/{txId}/sign', 'signPendingTx'],
  ['get', '/cooperatives/{coopId}/pending', 'getPendingTxs'],
  ['post', '/cooperatives/{id}/multisig-setup', 'setupMultisig'],
  ['post', '/cooperatives/{id}/transactions', 'initiateCoopTx'],
  ['get', '/coupons', 'getMyCoupons'],
  ['post', '/coupons', 'createCoupon'],
  ['post', '/coupons/validate', 'validateCoupon'],
  ['delete', '/coupons/{id}', 'deleteCoupon'],
  ['get', '/disputes', 'adminGetDisputes'],
  ['patch', '/disputes/{id}/resolve', 'adminResolveDispute'],
  ['get', '/export/orders', 'exportOrders'],
  ['patch', '/farmers/me', 'updateFarmerProfile'],
  ['get', '/farmers/me/bundle-discounts', 'getBundleDiscounts'],
  ['post', '/farmers/me/bundle-discounts', 'createBundleDiscount'],
  ['delete', '/farmers/me/bundle-discounts/{id}', 'deleteBundleDiscount'],
  ['put', '/farmers/me/bundle-discounts/{id}', 'updateBundleDiscount'],
  ['get', '/farmers/{id}', 'getFarmer'],
  ['get', '/favorites', 'getFavorites'],
  ['post', '/favorites', 'addFavorite'],
  ['get', '/favorites/check/{productId}', 'checkFavorite'],
  ['delete', '/favorites/{productId}', 'removeFavorite'],
  ['get', '/market/xlm-usdc', 'getMarketRate'],
  ['get', '/messages/unread-count', 'getUnreadMessageCount'],
  ['get', '/network', 'getNetwork'],
  ['delete', '/notifications/subscribe', 'unsubscribePush'],
  ['post', '/notifications/subscribe', 'subscribePush'],
  ['get', '/notifications/vapid-public-key', 'getPushPublicKey'],
  ['get', '/orders', 'getOrders'],
  ['post', '/orders', 'placeOrder'],
  ['get', '/orders/fee-preview', 'getFeePreview'],
  ['get', '/orders/sales', 'getSales'],
  ['get', '/orders/{id}/status', 'getOrderStatus'],
  ['patch', '/orders/{id}/status', 'updateOrderStatus'],
  ['post', '/orders/{orderId}/claim', 'claimEscrow'],
  ['post', '/orders/{orderId}/claim-preorder', 'claimPreorder'],
  ['post', '/orders/{orderId}/escrow', 'fundEscrow'],
  ['get', '/orders/{orderId}/receipt', 'downloadReceipt'],
  ['post', '/orders/{orderId}/return', 'fileReturn'],
  ['patch', '/orders/{orderId}/return/approve', 'approveReturn'],
  ['patch', '/orders/{orderId}/return/reject', 'rejectReturn'],
  ['get', '/products', 'getProducts'],
  ['post', '/products', 'createProduct'],
  ['post', '/products/bulk', 'uploadProductsCsv'],
  ['patch', '/products/bulk-price', 'bulkUpdatePrices'],
  ['get', '/products/categories', 'getCategories'],
  ['post', '/products/import', 'importProductsPreview'],
  ['post', '/products/import/confirm', 'importProductsConfirm'],
  ['get', '/products/mine/list', 'getMyProducts'],
  ['get', '/products/search', 'searchProducts'],
  ['post', '/products/upload-image', 'uploadProductImage'],
  ['delete', '/products/{id}', 'deleteProduct'],
  ['get', '/products/{id}', 'getProduct'],
  ['patch', '/products/{id}', 'updateProduct'],
  ['delete', '/products/{id}/flash-sale', 'cancelFlashSale'],
  ['patch', '/products/{id}/flash-sale', 'setFlashSale'],
  ['get', '/products/{id}/price-history', 'getPriceHistory'],
  ['patch', '/products/{id}/restock', 'restockProduct'],
  ['get', '/products/{id}/reviews', 'getProductReviews'],
  ['get', '/products/{id}/share', 'getProductShareMeta'],
  ['post', '/products/{id}/share', 'trackShareEvent'],
  ['get', '/products/{id}/tiers', 'getProductTiers'],
  ['post', '/products/{id}/tiers', 'updateProductTiers'],
  ['delete', '/products/{productId}/alert', 'removeStockAlert'],
  ['post', '/products/{productId}/alert', 'setStockAlert'],
  ['get', '/products/{productId}/alert/status', 'getMyAlert'],
  ['get', '/products/{productId}/calendar', 'getCalendar'],
  ['post', '/products/{productId}/calendar', 'setCalendarWeek'],
  ['get', '/products/{productId}/images', 'getProductImages'],
  ['post', '/products/{productId}/images', 'uploadProductImages'],
  ['patch', '/products/{productId}/images/reorder', 'reorderProductImages'],
  ['delete', '/products/{productId}/images/{imageId}', 'deleteProductImage'],
  ['post', '/products/{productId}/video', 'uploadProductVideo'],
  ['delete', '/products/{productId}/waitlist', 'leaveWaitlist'],
  ['post', '/products/{productId}/waitlist', 'joinWaitlist'],
  ['get', '/products/{productId}/waitlist/status', 'getWaitlistStatus'],
  ['get', '/rates/xlm-usd', 'getXlmRate'],
  ['get', '/recommendations', 'getRecommendations'],
  ['post', '/reviews', 'submitReview'],
  ['get', '/streams', 'getPaymentStreams'],
  ['post', '/streams', 'createPaymentStream'],
  ['post', '/streams/{id}/cancel', 'cancelPaymentStream'],
  ['patch', '/streams/{id}/decrease-rate', 'decreasePaymentStreamRate'],
  ['post', '/streams/{id}/withdraw', 'withdrawPaymentStream'],
  ['get', '/subscriptions', 'getSubscriptions'],
  ['post', '/subscriptions', 'createSubscription'],
  ['delete', '/subscriptions/{id}', 'cancelSubscription'],
  ['patch', '/subscriptions/{id}/pause', 'pauseSubscription'],
  ['patch', '/subscriptions/{id}/resume', 'resumeSubscription'],
  ['get', '/wallet', 'getWallet'],
  ['get', '/wallet/alerts', 'getAlerts'],
  ['patch', '/wallet/alerts/{id}/read', 'markAlertRead'],
  ['get', '/wallet/assets', 'getWalletAssets'],
  ['get', '/wallet/budget', 'getBudget'],
  ['patch', '/wallet/budget', 'setBudget'],
  ['post', '/wallet/claim', 'claimBalance'],
  ['get', '/wallet/claimable-balances', 'getClaimableBalances'],
  ['get', '/wallet/earnings', 'getCreatorEarnings'],
  ['post', '/wallet/earnings/claim', 'claimCreatorEarnings'],
  ['post', '/wallet/fund', 'fundWallet'],
  ['post', '/wallet/merge', 'mergeWallet'],
  ['get', '/wallet/path-estimate', 'getPathEstimate'],
  ['post', '/wallet/send', 'sendXLM'],
  ['get', '/wallet/transactions', 'getTransactions'],
  ['delete', '/wallet/trustline', 'removeTrustline'],
  ['post', '/wallet/trustline', 'addTrustline'],
  ['post', '/wallet/withdraw', 'withdrawFunds'],
];

const PUBLIC_OPERATIONS = new Set([
  'getAnnouncements',
  'getAuction',
  'getAuctionBids',
  'getAuctions',
  'getCalendar',
  'getCategories',
  'getFarmer',
  'getMarketRate',
  'getNetwork',
  'getPriceHistory',
  'getProduct',
  'getProductImages',
  'getProductReviews',
  'getProductShareMeta',
  'getProductTiers',
  'getProducts',
  'getXlmRate',
  'ensureCsrfToken',
  'refresh',
  'login',
  'recoverAccount',
  'register',
  'searchProducts',
]);

function toTitle(operationId) {
  return operationId.replace(/([A-Z0-9])/g, ' $1').replace(/^./, (c) => c.toUpperCase()).trim();
}

function buildSpaPaths() {
  const paths = {};
  for (const [method, path, operationId] of SPA_ENDPOINTS) {
    const fullPath = `/api/v1${path}`;
    const params = [...path.matchAll(/\{(\w+)\}/g)].map(([, name]) => ({
      name,
      in: 'path',
      required: true,
      schema: { type: 'string' },
    }));
    paths[fullPath] = paths[fullPath] || {};
    paths[fullPath][method] = {
      operationId,
      summary: toTitle(operationId),
      tags: [path.split('/')[1]],
      ...(params.length && { parameters: params }),
      ...(!PUBLIC_OPERATIONS.has(operationId) && { security: [{ bearerAuth: [] }] }),
      responses: { 200: { description: 'Success' } },
    };
  }

  // #1379: orders are rejected without a UUID v4 idempotency key.
  paths['/api/v1/orders'].post.parameters = [
    {
      name: 'X-Idempotency-Key',
      in: 'header',
      required: true,
      description: 'UUID v4, generated once per checkout attempt and reused for its retries',
      schema: { type: 'string', format: 'uuid' },
    },
  ];
  return paths;
}

module.exports = { SPA_ENDPOINTS, buildSpaPaths };
